apiVersion: v1
kind: Service
metadata:
  name: file-uploader-backend-service
  labels:
    app: file-uploader
    tier: backend
spec:
  type: NodePort
  selector:
    app: file-uploader-backend
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-uploader-backend-deploy
  labels:
    app: file-uploader-backend
    tier: backend
spec:
  selector:
    matchLabels:
      app: file-uploader-backend
  template:
    metadata:
      labels:
        app: file-uploader-backend
    spec:
      containers:
      - name: file-uploader-backend
        image: moosterhuis/file_uploader_backend:v3
        ports:
        - containerPort: 8081
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/postgres